[package]
name = "hello-tera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.17"
lazy_static = "1.4"
serde_json = "1.0"
